<?php

namespace AppBundle\Repository;

/**
 * ProgramPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramPointRepository extends \Doctrine\ORM\EntityRepository
{
}
